collections_config:
  pages:
    path: .
    glob:
      - '*.html'
    icon: article
    disable_url: false
    _enabled_editors:
      - visual
      - content
    disable_add: true
    disable_add_folder: false
    disable_file_actions: false
  content:
    path: content
    glob:
      - '*.json'
    icon: ''
    disable_url: false
    _enabled_editors:
      - visual
      - data
    disable_add: true
    disable_add_folder: false
    disable_file_actions: false
file_config:
  index.html:
    label: Home
    url: /
  products.html:
    label: Products
    url: /products.html
  solutions.html:
    label: Solutions
    url: /solutions.html
  resources.html:
    label: Resources
    url: /resources.html
  about.html:
    label: About
    url: /about.html
  contact.html:
    label: Contact
    url: /contact.html
  content/home.json:
    label: Home Content
    url: /
    _enabled_editors:
      - visual
      - data
  content/products.json:
    label: Products Content
    url: /products.html
    _enabled_editors:
      - visual
      - data
  content/solutions.json:
    label: Solutions Content
    url: /solutions.html
    _enabled_editors:
      - visual
      - data
  content/resources.json:
    label: Resources Content
    url: /resources.html
    _enabled_editors:
      - visual
      - data
  content/about.json:
    label: About Content
    url: /about.html
    _enabled_editors:
      - visual
      - data
  content/contact.json:
    label: Contact Content
    url: /contact.html
    _enabled_editors:
      - visual
      - data
editor:
  default_path: /index.html
timezone: Etc/UTC
